### PR TITLE
fix bug in gru layer

### PR DESCRIPTION
**Pull request by qizhex**
The decoder gru_layer doesn't take output from encoder as initialization of the hidden state.

### CODE REVIEW

**Comment by orhanf** [comment]
Thank you @cheezer , merging.

**Comment by bastings** [comment]
@orhanf was this really a bug?

**Comment by orhanf** [comment]
@bastings, this was not a bug, but you were not able to use the simple gru layer as decoder since it was always using zero initial state. This PR allows you to specify the initial hidden state of the simple gru layer hence making it possible to be used as the decoder. 

In short, this PR is not a bug fix but an incremental feature :)

**Comment by bastings** [comment]
thanks @orhanf 
so it's basically a gru_cond_simple_layer (session1) now ;)

**Comment by orhanf** [comment]
yes exactly :)

**Comment by qizhex** [comment]
Sorry I kept using session 3 and I thought the gru_layer can also be used for decoding. It's good to be able to change to the simple gru by passing parameters in session 3.  :)

**Pull request merged**
